{
 "title": "Spring Boot Todo Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request runtime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "rate(api_todo_get_seconds_count[$__rate_interval])",
     "legendFormat": "GET /api/todo"
    },
    {
     "expr": "rate(api_todo_post_seconds_count[$__rate_interval])",
     "legendFormat": "POST /api/todo"
    },
    {
     "expr": "rate(api_todo_delete_seconds_count[$__rate_interval])",
     "legendFormat": "DELETE /api/todo/{id}"
    },
    {
     "expr": "rate(api_todo_put_seconds_count[$__rate_interval])",
     "legendFormat": "PUT /api/todo"
    }
   ]
  },
  {
   "title": "Request/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{method=\"GET\"}[$__rate_interval]))",
     "legendFormat": "GET /api/todo"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{method=\"POST\"}[$__rate_interval]))",
     "legendFormat": "POST /api/todo"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{method=\"DELETE\"}[$__rate_interval]))",
     "legendFormat": "DELETE /api/todo/{id}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{method=\"PUT\"}[$__rate_interval]))",
     "legendFormat": "PUT /api/todo"
    }
   ]
  },
  {
   "title": "GCHeapSummary HeapUsed vs HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{uri=\"/api/todo\", method=\"GET\"}[$__rate_interval]))",
     "legendFormat": "GET /api/todo"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{uri=\"/api/todo\", method=\"POST\"}[$__rate_interval]))",
     "legendFormat": "POST /api/todo"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{uri=\"/api/todo/{id}\", method=\"DELETE\"}[$__rate_interval]))",
     "legendFormat": "DELETE /api/todo"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{uri=\"/api/todo\", method=\"PUT\"}[$__rate_interval]))",
     "legendFormat": "PUT /api/todo"
    },
    {
     "expr": "rate(jdk_GCHeapSummaryheapUsed[$__rate_interval])",
     "legendFormat": "GCHeapSummaryheapUsed"
    }
   ]
  },
  {
   "title": "CPU Load vs HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{uri=\"/api/todo\", method=\"GET\"}[$__rate_interval]))",
     "legendFormat": "GET /api/todo"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{uri=\"/api/todo\", method=\"POST\"}[$__rate_interval]))",
     "legendFormat": "POST /api/todo"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{uri=\"/api/todo/{id}\", method=\"DELETE\"}[$__rate_interval]))",
     "legendFormat": "DELETE /api/todo"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{uri=\"/api/todo\", method=\"PUT\"}[$__rate_interval]))",
     "legendFormat": "PUT /api/todo"
    },
    { "expr": "jdk_CPULoadmachineTotal", "legendFormat": "CPULoadmachineTotal" }
   ]
  }
 ]
}